name: OrangeFox - Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: 🦊 Building OrangeFox Recovery
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: OrangeFox Build
      uses: UWU-TEAM/UWU-OrangeFox-Builder@v1.0.0
      with:
        USER_NAME: 'Ayyas-RF'
        USER_EMAIL: 'berrzert9@gmail.com'
        DEVICE_TREE: 'https://github.com/Ayyas-RF/device_xiaomi_chime-recovery/'
        DEVICE_TREE_BRANCH: 'fox-12.1'
        DEVICE_PATH: 'device/xiaomi/chime'
        DEVICE_NAME: 'chime'
        BUILD_TARGET: 'recovery'
        MAINTAINER_URL: 'https://ibb.co.com/7JXPHvTT'
        GH_RELEASE: 'true'
